### ISSUE TITLE
Add pre-emptive basic auth as an option when using with_credentials()

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/openapi-common#636]
### 📝 Description of the feature

In some scenarios it's desirable to specify pre-emptive basic auth as an authorization mode, instead of relying on the 401 response to negotiate the available authorization mode.

We should allow a user to specify they wish to use pre-emptive basic auth, either as an additional optional keyword argument somewhere, or an environment variable that controls the execution.

**Comment by da1910** [comment]
Per previous discussion I dislike adding a special option here, I would prefer us to enable pre-emptive authentication where possible for all the auth methods. It's definitely a thing we can do for NTLM and Negotiate (although I don't know if requests-negotiate-sspi offers it as an option).

I would suggest it becomes a kwarg on the `with_method()` methods where supported and skips the initial validation. We should document adding the feature and where it is supported.

**Comment by Andy-Grigg** [comment]
`requests-negotiate-sspi` doesn't allow the choice of NTLM vs kerberos, but what we can do as a somewhat generic implementation is:

* Define a new enum `AuthMode`, with the values auto, basic, ntlm, negotiate, kerberos.
* For `with_credentials`, define a new kwarg set to `auto` by default, which does the initial request stuff. If basic is specified, do that, and if ntlm or negotiate is specified, do HttpNtlmAuth. If kerberos is specified, raise a ValueError (httpntlmauth doesn't do kerberos, as the name implies)
* For `with_autologon`, define a new kwarg set to `auto` by default, which does the initial request stuff. If negotiate is specified, or if kerberos is specified and the user is on Linux), use requests-negotiage-sspi or negotiate-kerberos. Otherwise, raise a ValueError

I think given the level of control the authentication libraries give us, this is probably the best we can do.

**Comment by Andy-Grigg** [comment]
As discussed in the PR, we've reduced the enum to the values of auto, basic, and ntlm, and are using it only for the `with_credentials` method. This is because the libraries we're using for `with_autologon` don't properly support pre-emptive auth, and don't allow more fine-grained control on the particular implementation of gssapi that gets used.
