### ISSUE TITLE
Recommend the use of `pip-system-certs` 

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/openapi-common#649]
As a result of the issue seen in #637, we are settling on the idea to use `pip-system-certs` to address this issue, since it essentially does what we would do manually (i.e. look in system pre-defined paths for private CA certificates) but does it automatically by leveraging the system-wide OpenSSL configuration via the python ssl module.

We should decide how we want to do this:

* Include as a dependency of this package
* Include as a dependency of this package in the OIDC extra (since this is when it's actually required, see #637), and recommend its use in documentation in other situations
* Only recommend its use and don't install by default at all

The reason for not just including as a dependency in all situations is that it is very side-effect-y, in that it patches all instances of `pip` and `requests` at runtime. If a user isn't expecting this then it could be confusing.

Maybe we add it as an additional extra?

@ansys/matbu-project-maintainers Comments welcome on which way to go with this.

**Comment by Andy-Grigg** [comment]
This is added to the README, and therefore also on the PyPI pAge, but doesn't appear in the generated HTML documentation. @da1910 was that intentional?

**Comment by da1910** [comment]
No, I naively assumed that rather than having two copies of the exact same text, the same would appear in both places...

**Comment by Andy-Grigg** [comment]
I thought we had the 'include' functionality implemented here, but it looks like we don't. The HTML docs RST source and the README are separate, even though they're both RST docs.

I'll close this, and create a new ticket to merge the README with the rest of the docs where relevant.
